### ISSUE TITLE
[Unix] Introdução ao rsync

### ISSUE THREAD

**Issue by hugobessaa** [LFeh/poste-mais#26]
Ferramenta incrível para transferência de arquivos. Pouquíssimos posts falam sobre ele.

Referências:
- http://linux.die.net/man/1/rsync

**Comment by willianjusten** [comment]
Opa, esse muito me interessa, é uma ferramenta indispensável para mim quando não uso CI.

**Comment by hugobessaa** [comment]
@willianjusten tá usando CI para deploy? Opa, outra pauta aí hein! hahaha. Seu blog tem repositório público?

**Comment by willianjusten** [comment]
Opa, eu uso CI para deploy sim, não no blog, pq ele está no github pages e sei lá pq, nem fiz hauahua
Mas posso escrever sobre sim, acho um assunto muito interessante.

**Comment by hugobessaa** [comment]
Legal :+1:

**Comment by vitorbritto** [comment]
Mais um artigo que vai sair da gaveta em breve. Explicarei o que é o Rsync, como utilizar e fazer sincronização entre ambientes. Mas antes vou falar do SSH (chave pública e privada que algumas pessoas se batem ainda) e um pouco sobre SCP. Daí, alguém pode aproveitar e fazer o gancho com o Gulp. Eu posso fazer com o Grunt.

Cc: @hugobessaa @willianjusten @fdaciuk @LFeh

**Comment by fdaciuk** [comment]
Show @vitorbritto! Posso fazer um com Gulp xD

**Comment by fdaciuk** [comment]
Feito! :dancer: :dancer: 

Deploy com Rsync no GulpJS:
http://blog.da2k.com.br/2015/01/27/gulpjs-deploy-com-rsync/

**Comment by hugobessaa** [comment]
Muito bom @fdaciuk !

**Comment by fdaciuk** [comment]
@hugobessaa o/
