### ISSUE TITLE
[Repositório] Alteração de nome?

### ISSUE THREAD

**Issue by LFeh** [LFeh/poste-mais#32]
Como sugerido pelo @hugobessaa, [nesse comentário](https://github.com/LFeh/1-post-por-dia/issues/18#issuecomment-71019150), talvez seja interessante mudar o nome do repositório para ficar mais claro o objetivo.

Algumas questões:

* Mudar para qual nome?
* Tem como referenciar o link com o nome antigo para o novo? (para não perder os links que estão pela internet afora)

c/c @fdaciuk @willianjusten

**Comment by jugoncalves** [comment]
O TJ Holowaychuk fez umas macumbarias de trocar o user deles e apontar pro novo (tj ao invés de visionmedia). Talvez role fazer isso.

**Comment by LFeh** [comment]
Tem alguma ideia de como fazer essa magica? Deu uma procurada aqui e não achei nada... :(

**Comment by willianjusten** [comment]
Precisaria fazer um redirect 302 para isso. Mas te falar que não sei como funcionaria esse apontamento não hein ahuahua

Por mim, pode mudar, eu meio que entrei na onda para participar junto com o @fdaciuk no início, mas não me incomodo de mudar, até pq só ele que tá mitando no #1postperday, eu falhei em alguns dias...

E se eu continuar escrevendo posts grandes como o último, vou fazer #1postperweek ahuahua

**Comment by LFeh** [comment]
@willianjusten, o problema do nome #1postperda é que acaba dando uma assustada na galera, achando que o repositório é só para quem quer participar essa mitagem de vocês :p 

Eu tinha usado esse nome como uma analogia e para referenciar com a ideia do @fdaciuk, mas acabou não dando tão certo, hehe.

**Comment by hugobessaa** [comment]
Sugestões para nome:

- pautas
- ideias
- poste-mais

**Comment by jugoncalves** [comment]
"poste-mais" +1

também sugiro "escreva".

**Comment by jugoncalves** [comment]
Não achei também como ele fez isso. Anyway, vc pode criar um repo com mesmo nome dizendo: oi, mudamos :smile:.

**Comment by willianjusten** [comment]
Acho legal o "poste-mais"

**Comment by jorgekury** [comment]
"poste-mais-sobre"

**Comment by jorgekury** [comment]
"compartilhe-mais" acho maneiro também, por que as vezes o cara não que escrever, mais sim fazer um vídeo sei lá

**Comment by willianjusten** [comment]
Opa, muito boa @jorgekury , achei esse nome perfeito.

**Comment by matheusmmo** [comment]
Gostei do compartilhe-mais também!

Em 22 de janeiro de 2015 12:04, Willian Justen <notifications@github.com>
escreveu:

> Opa, muito boa @jorgekury <https://github.com/jorgekury> , achei esse
> nome perfeito.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LFeh/1-post-por-dia/issues/32#issuecomment-71024198>.
>



--

**Comment by hugobessaa** [comment]
"compartilhe-mais" +1!

**Comment by fdaciuk** [comment]
compartilhe-mais é legal :D :+1: 
Acho que nem precisa redirecionar.. muda o nome desse e cria um novo com o mesmo nome.. ae no novo, você só coloca o link desse no README, dizendo que foi mudado xD

**Comment by bernardodiasc** [comment]
> muda o nome desse e cria um novo com o mesmo nome.. ae no novo, você só coloca o link desse no README, dizendo que foi mudado xD

boa ideia.

sugestão: coloca o resultado parcial da enquete no topico dessa issue.

+1 para "pautas"

**Comment by hugobessaa** [comment]
Eu acabei de trocar o nome de um repositório. O Github faz o redirect automaticamente dos links antigos para os novos.

**Comment by LFeh** [comment]
Sério @hugobessaa? Que boa noticia! :D 

Também voto no ***compartilhe-mais***

Temos então:

1. compartilhe-mais = 5 votos
2. poste-mais = 2
3. pautas = 1


É isso mesmo? Vamos definir o nome até hoje a noite :+1:

**Comment by raphaelfabeni** [comment]
Meu voto vai pra *poste-mais*

**Comment by hugobessaa** [comment]
Então, compartilhe-mais ganhou?

Acho poste-mais interessante por ser menor.

**Comment by fdaciuk** [comment]
Pensando bem, post-mais é mais interessante pra usar como hashtag também pra divulgar o repo xD
-1 compartilhe-mais
+1 post-mais xD

**Comment by LFeh** [comment]
hahaha, e agora pessoal?

Realmente poste-mais, faz mais sentido com a ideia do Repo, já que ele tem haver com postagens em si. E como o nome é menor, é mais fácil divulgar.

Todos de acordo?

**Comment by fdaciuk** [comment]
:+1:

**Comment by jorgekury** [comment]
Manda bala ;)

**Comment by hugobessaa** [comment]
:+1:
Em sex, 23 de jan de 2015 às 09:00, Fernando Daciuk <
notifications@github.com> escreveu:

**Comment by williamcosta** [comment]
+1 poste-mais

**Comment by jugoncalves** [comment]
:+1:

**Comment by raphaelfabeni** [comment]
:metal:

**Comment by LFeh** [comment]
Feito \o/
