### ISSUE TITLE
Participantes

### ISSUE THREAD

**Issue by gpedro** [LFeh/poste-mais#34]
seria legal deixar no__README.md__ o link do blog que está participando desse desafio de __#1postperday__.

:facepunch:

**Comment by LFeh** [comment]
O que acham pessoal?

Com essa mudança de proposta de repo, será que compensa?

@fdaciuk @willianjusten @hugobessaa e demais interessados.

**Comment by fdaciuk** [comment]
Pois é.. como mudou o nome, acho que não faz muito sentido agora.
Mas daria pra colocar os blogs que estão usando assuntos daqui pra postar, ae acho que faria sentido :)

**Comment by matheusmmo** [comment]
Concordo com o Fernando!

Em 23 de janeiro de 2015 13:49, Fernando Daciuk <notifications@github.com>
escreveu:

> Pois é.. como mudou o nome, acho que não faz muito sentido agora.
> Mas daria pra colocar os blogs que estão usando assuntos daqui pra postar,
> ae acho que faria sentido :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LFeh/poste-mais/issues/34#issuecomment-71213056>.
>



--

**Comment by LFeh** [comment]
Show @fdaciuk, curti a ideia.

Conseguem levantar os blogs que estão aderindo?

**Comment by hugobessaa** [comment]
Um "como visto em" seria legal hahaha. Um contador também seria uma boa. "Já foram escritos 100 mil posts com pautas deste repositório" :+1:

**Comment by fdaciuk** [comment]
Quer ver contar os posts haha! Mas a ideia é boa @hugobessaa :dancer: :dancer:

**Comment by jorgekury** [comment]
Achei maneiro, a ideia do contador que seria trampo ! :) tem meu apoio galera

**Comment by jorgekury** [comment]
Porem, tendo em vista que as pessoas estão cada vez mais aderindo, acho que vai chegar um ponto que vai ter muito artigo pra controlar, sei lá tem que elaborar

**Comment by ericdouglas** [comment]
Pode criar uma issue aqui chamada **Contador**, onde a pessoa ao criar o artigo, posta o link nessa issue e faz referência com `#número-da-issue` para ficar registrado de qual série de artigos ela tirou ideia

:smile:

**Comment by ericdouglas** [comment]
ps: criei a issue #35

**Comment by jorgekury** [comment]
Esse @ericdouglas é manjadador mesmo em !

**Comment by ericdouglas** [comment]
Github <3 hauhauhahua

**Comment by ericdouglas** [comment]
Boa @jorgekury ! Contador funcionando! :smiley:

**Comment by fdaciuk** [comment]
Mas como conta? Manualmente? O Github não mostra a quantidade de referências, certo? Só uma abaixo da outra :P

**Comment by jorgekury** [comment]
Se o pessoa "respeitar" a issue de contador,  da pra ter uma ideia pelo numero de comentários dela !

**Comment by jorgekury** [comment]
Só que seria por exemplo, post relacionados a campanha "poste-mais" e não para cada issues

**Comment by ericdouglas** [comment]
Isso que o @jorgekury falou. Vai dar para contar pelo número de comentários, e fica a referência na issue dos artigos que foram feitos.

Ex: Se você olhar na issue do tema X que te interessa, ao acompanhar ali você consegue ver tudo que já foi feito por essas citações.

E o contador geral será o *balãozinho* dos comments :smile:

**Comment by fdaciuk** [comment]
Tendi xD
Mas se mais alguém comentar na issue do artigo, já vai zuar a contagem, haha :stuck_out_tongue_winking_eye:

**Comment by ericdouglas** [comment]
Se a pessoa comentar, ela fica **obrigada** a escrever um artigo e alterar o comentário colocando o link do artigo no lugar uhauhauahauh

Mas bem lembrado @fdaciuk , vou colocar um aviso lá! :+1:

**Comment by fdaciuk** [comment]
haeuhaeuh! Boa @ericdouglas! Comentou, se comprometeu :stuck_out_tongue_winking_eye:

**Comment by ericdouglas** [comment]
Avisei lá! Se a pessoa comentar agora, merece um prêmio! :trophy:

**Comment by jorgekury** [comment]
Não tem como moderar @ericdouglas  e @fdaciuk  ?

**Comment by gpedro** [comment]
que tal criar uma issue para ser referência a um post? Apesar de nem todos blog ser opensource, mas daria pra fazer isso...

**Comment by jorgekury** [comment]
Como assim ?

**Comment by ericdouglas** [comment]
Acho que não tem @jorgekury .

@gpedro não sei se entendi, mas se cada post virar uma issue, ai tem a opção de deixar a issue com a milestone Artigos, que daria para fazer a contagem também, mas acho que fazer um comentário na issue **Contador** mais simples

**Comment by hugobessaa** [comment]
Ou então não contamos… Manter isso seria chato, na minha opinião. Cada issue já recebe comentário com os links que foram publicadas sobre ela.

O menos chato que poderíamos fazer seria contar a quantidade de assuntos publicados, dado uma olhada na tag Concluido :)

**Comment by LFeh** [comment]
Gostei da ideia do contador. Vamos testar.

As Issues tem gerado debates interessantes, pelo que entendi não tem problema de ter outros comentários na Issue, certo?

**Comment by gpedro** [comment]
As que forem feitas, apenas será colocado como tag concluída e deixada aberta? Isso não atrapalhará na listagem quando houver bastante feitas e solicitadas?

**Comment by LFeh** [comment]
Acho justo manter aberta. Pode ter mais gente interessada em escrever sobre o mesmo tema.

**Comment by ericdouglas** [comment]
Concordo @LFeh ! Creio que deixar aberto é melhor, a pessoa pode filtrar pela label!
