### ISSUE TITLE
Contador de Artigos

### ISSUE THREAD

**Issue by ericdouglas** [LFeh/poste-mais#35]
Ao criar um artigo com algum tema dos sugeridos neste projeto, comente nessa issue e faça referência ao tema/issue usando o `#número-da-issue`.

# WARNING

**ESSA ISSUE NÃO É PARA DISCUSSÕES, APENAS PARA TERMOS UM CONTROLE DO NÚMERO DE ARTIGOS CRIADOS A PARTIR DESTE PROJETO, ENTÃO APENAS COMENTE QUANDO FOR PARA REFERENCIAR UM ARTIGO ESCRITO QUE USOU ALGUM DOS TEMAS AQUI PROPOSTOS!!!1!!1!!1**

**Comment by jorgekury** [comment]
Issue #18 
Um pouco de como conheci essa linguagem linda <3 

http://www.jkury.com/como-aprendi-javascript

**Comment by woliveiras** [comment]
Issue #13 
Como eu me preparei (E como estou me especializando) para o mercado de Front End:

http://woliveiras.com.br/requisitos-para-vagas-front-end/

**Comment by LFeh** [comment]
Issue #12 

[Meu dia a dia como desenvolvedor Front-End](http://www.felipefialho.com/blog/2015/meu-dia-a-dia-como-dev-frontend/)

**Comment by raphaelfabeni** [comment]
Issue #8 

[Git: Alterando commits - parte 1](http://www.raphaelfabeni.com.br/git-alterando-commits-parte-1/)

**Comment by fdaciuk** [comment]
Issue #26 

[GulpJS - Deploy com Rsync](http://blog.da2k.com.br/2015/01/27/gulpjs-deploy-com-rsync/)

**Comment by jorgekury** [comment]
Issue #13 
[Como me tornei um Front-End](http://www.jkury.com/como-me-tornei-um-frontend/)

**Comment by willianjusten** [comment]
Issue https://github.com/LFeh/poste-mais/issues/20

[Perguntas e Respostas - Jekyll](http://willianjusten.com.br/perguntas-e-respostas-jekyll/)

**Comment by willianjusten** [comment]
Issue https://github.com/LFeh/poste-mais/issues/12

[Meu dia a dia como Dev Front End](http://willianjusten.com.br/meu-dia-a-dia-como-dev-frontend/)

**Comment by jorgekury** [comment]
Issue #7 
[Seu código não é uma obra prima]http://www.jkury.com/seu-codigo-nao-e-uma-obra-prima

**Comment by fdaciuk** [comment]
Issue #36 
[Code Coverage em JS](http://blog.da2k.com.br/2015/01/07/code-coverage-em-javascript/)
[Pensando TDD com JS](http://blog.da2k.com.br/2015/01/06/pensando-tdd-com-javascript/)

**Comment by fdaciuk** [comment]
Issue #36 
[Pensando TDD com JS](http://blog.da2k.com.br/2015/01/06/pensando-tdd-com-javascript/)

**Comment by jugoncalves** [comment]
Issue meio #13 meio #18

[How to start with JavaScript Programming](http://jugoncalv.es/blog/javascript/how-to-start-with-javascript/)

**Comment by mjnr** [comment]
Issue #47
 - HarpJS, um gerador estático simpático.

**Comment by raphaelfabeni** [comment]
Issue #8 

[Git: Alterando seus commits com rebase - parte 2/2](http://www.raphaelfabeni.com.br/git-alterando-commits-parte-2/)

**Comment by raphaelfabeni** [comment]
Issue #45 

[GitHub: Atualizando seu fork](http://www.raphaelfabeni.com.br/atualizando-seu-fork/)

**Comment by LFeh** [comment]
Issue #1 

O @felquis postou: 

[Como minificar e concatenar scripts AngularJS com GulpJS](http://tutsmais.com.br/blog/angularjs/como-minificar-e-concatenar-scripts-angularjs-com-gulpjs/)

**Comment by lukaswilkeer** [comment]
Não é referente a nenhuma issue, mas sim ao projeto como todo, o qual me incentivou a postar.
@ericdouglas este post pode fazer parte do contador?

[Stream do twitter usando node.js](http://lukaswilkeer.github.io/nodejs/2015/02/07/stream-do-twitter-usando-nodejs.html)

**Comment by woliveiras** [comment]
Issue #45 

[Contribuindo para projetos Open Source no Github mesmo sendo iniciante](http://woliveiras.com.br/contribuindo-para-projetos-open-source-no-github-mesmo-sendo-iniciante/)

**Comment by randsonjs** [comment]
Como encontrar desenvolvedores qualificados? #49

**Comment by raphaelfabeni** [comment]
Issue #9 
[Compartilhe seu conhecimento](http://www.raphaelfabeni.com.br/compartilhe-conhecimento/)

**Comment by robsonbittencourt** [comment]
Issue #50 

[Hospendando seu Blog Na AWS por Centavos](http://rbittencourt.com/hospedando-seu-blog-na-aws-por-centavos/)
