### ISSUE TITLE
É necessário saber Java? 

### ISSUE THREAD

**Issue by felipesousa** [LFeh/poste-mais#59]
A pergunta pode parecer idiota pra área de Front End, mais gostaria de saber de quem trabalha com projetos, se é de fato necessário saber Java, se ele conta em currículo, ou se influência em algo, e se vocês usam ou já usaram em algum projeto! Gostaria de saber a opinião de vocês sobre o assunto.

Obrigado e abraço :)

**Comment by hugobessaa** [comment]
Se você quer se abrir a possibilidade de trabalhar em uma empresa que usa Java no back-end, então talvez você queira saber como usar JSP.

Existem tantas coisas a mais para estudar e se tornar um bom front-end que isso não estaria na minha lista de estudos.

**Comment by felipesousa** [comment]
Cara obrigado, de fato não pretendo estudar Java, pois creio eu que o que tem de Java pra se aplicar por aí é relativamente pequeno em relação a outras coisas. Obrigado :)
